[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn apps.api.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "api"

[services.variables]
PORT = "8000"
PYTHONPATH = "/app"
